Repository kubescape/storage, pull requests merged in 2023-12, with the labels that each got.

#65 support known servers
  artifacts/knownservers/01-example.yaml
  pkg/apis/softwarecomposition/network_types.go
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy.go
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy_test.go
  pkg/apis/softwarecomposition/register.go
  pkg/apis/softwarecomposition/v1beta1/network_types.go
  pkg/apis/softwarecomposition/v1beta1/register.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go
  pkg/apis/softwarecomposition/validation/validation.go
  pkg/apis/softwarecomposition/validation/validation_test.go
  pkg/apis/softwarecomposition/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_knownserver.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_softwarecomposition_client.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/knownserver.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/softwarecomposition_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/interface.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/knownserver.go
  pkg/generated/listers/softwarecomposition/v1beta1/expansion_generated.go
  pkg/generated/listers/softwarecomposition/v1beta1/knownserver.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/file/generatednetworkpolicy.go
  pkg/registry/softwarecomposition/knownservers/etcd.go
  pkg/registry/softwarecomposition/knownservers/strategy.go
Labels: enhancement, release, Refactoring

#72 Add known servers
  pkg/registry/file/generatednetworkpolicy.go
  pkg/registry/file/storage.go
Labels: enhancement

#73 Trigger
  pkg/registry/file/vulnerabilitysummarystorage_test.go
Labels: release, Tests

#71 docs: How to work with Storage
  README.md
  hack/update-codegen.sh
Labels: documentation

#70 Cleanup resources
  go.mod
  go.sum
  main.go
  pkg/cleanup/cleanup.go
  pkg/cleanup/cleanup_test.go
  pkg/cleanup/discovery.go
  pkg/cleanup/discovery_test.go
  pkg/cleanup/testdata/data.zip
  pkg/cleanup/testdata/imageids.json
  pkg/cleanup/testdata/instanceids.json
  pkg/cleanup/testdata/wlids.json
  pkg/cleanup/utils.go
  pkg/cleanup/utils_test.go
  pkg/registry/file/configurationscansummarystorage.go
  pkg/registry/file/generatednetworkpolicy.go
  pkg/registry/file/storage.go
  pkg/registry/file/storage_test.go
  pkg/registry/file/vulnerabilitysummarystorage.go
Labels: enhancement

#74 merge ports
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy.go
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy_test.go
Labels: release

#76 add np tests
  .github/workflows/pr-merged.yaml
Labels: Tests

#75 Updating the syft format
  Makefile
  README.md
  go.mod
  go.sum
  pkg/apis/softwarecomposition/packagemetadata/packagemetadata.go
  pkg/apis/softwarecomposition/syfttypes.go
  pkg/apis/softwarecomposition/v1beta1/syfttypes.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go
  pkg/apis/softwarecomposition/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: enhancement, Tests

#78 Delete application profiles based on template hash
  go.mod
  go.sum
  pkg/cleanup/cleanup.go
  pkg/cleanup/discovery.go
Labels: release, bug_fix
