Repository kubescape/storage, pull requests merged in 2023-09, with the labels that each got.

#41 Vuln summary api objects
  .gitignore
  pkg/apis/softwarecomposition/register.go
  pkg/apis/softwarecomposition/types.go
  pkg/apis/softwarecomposition/types_test.go
  pkg/apis/softwarecomposition/v1beta1/register.go
  pkg/apis/softwarecomposition/v1beta1/types.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go
  pkg/apis/softwarecomposition/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_softwarecomposition_client.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_vulnerabilitysummary.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/softwarecomposition_client.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/vulnerabilitysummary.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/interface.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/vulnerabilitysummary.go
  pkg/generated/listers/softwarecomposition/v1beta1/expansion_generated.go
  pkg/generated/listers/softwarecomposition/v1beta1/vulnerabilitysummary.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/file/vulnarabilitysummarystoarge.go
  pkg/registry/file/vulnarabilitysummarystoarge_test.go
  pkg/registry/softwarecomposition/vulnerabilitysummary/etcd.go
  pkg/registry/softwarecomposition/vulnerabilitysummary/strategy.go
Labels: enhancement, release

#42 Add applicationprofile and summary types
  pkg/apis/softwarecomposition/register.go
  pkg/apis/softwarecomposition/types.go
  pkg/apis/softwarecomposition/v1beta1/register.go
  pkg/apis/softwarecomposition/v1beta1/types.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go
  pkg/apis/softwarecomposition/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/applicationactivity.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/applicationprofile.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/applicationprofilesummary.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_applicationactivity.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_applicationprofile.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_applicationprofilesummary.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_softwarecomposition_client.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/softwarecomposition_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/applicationactivity.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/applicationprofile.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/applicationprofilesummary.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/interface.go
  pkg/generated/listers/softwarecomposition/v1beta1/applicationactivity.go
  pkg/generated/listers/softwarecomposition/v1beta1/applicationprofile.go
  pkg/generated/listers/softwarecomposition/v1beta1/applicationprofilesummary.go
  pkg/generated/listers/softwarecomposition/v1beta1/expansion_generated.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/softwarecomposition/applicationactivity/etcd.go
  pkg/registry/softwarecomposition/applicationactivity/strategy.go
  pkg/registry/softwarecomposition/applicationprofile/etcd.go
  pkg/registry/softwarecomposition/applicationprofile/strategy.go
  pkg/registry/softwarecomposition/applicationprofilesummary/etcd.go
  pkg/registry/softwarecomposition/applicationprofilesummary/strategy.go
Labels: enhancement

#43 gofmt on project
  pkg/admission/wardleinitializer/interfaces.go
  pkg/admission/wardleinitializer/wardleinitializer.go
  pkg/admission/wardleinitializer/wardleinitializer_test.go
  pkg/apis/softwarecomposition/install/install.go
  pkg/apis/softwarecomposition/install/roundtrip_test.go
  pkg/apis/softwarecomposition/validation/validation.go
  pkg/apiserver/scheme_test.go
  pkg/registry/file/watch.go
  pkg/registry/softwarecomposition/sbomspdxv2p3/strategy.go
  pkg/registry/softwarecomposition/sbomspdxv2p3filtered/strategy.go
  pkg/registry/softwarecomposition/sbomsummary/strategy.go
  pkg/registry/softwarecomposition/vulnerabilitymanifest/strategy.go
  pkg/registry/softwarecomposition/vulnerabilitymanifestsummary/strategy.go
  pkg/registry/softwarecomposition/workloadconfigurationscans/strategy.go
  pkg/registry/softwarecomposition/workloadconfigurationscansummary/strategy.go
Labels: release, Refactoring

#44 The returned order in the list is not always the same
  pkg/registry/file/vulnarabilitysummarystoarge_test.go
Labels: Bug fix
