Repository kubescape/storage, pull requests merged in 2023-10, with the labels that each got.

#55 Setting up project info in repo
  MAINTAINERS.md
  README.md
  SECURITY-INSIGHTS.yml
  SECURITY.md
  SECURITY_CONTACTS
Labels: documentation

#54 Vex support
  artifacts/openvulnerabilityexchangecontainer/example-01.yaml
  go.mod
  go.sum
  pkg/apis/softwarecomposition/register.go
  pkg/apis/softwarecomposition/types.go
  pkg/apis/softwarecomposition/v1beta1/register.go
  pkg/apis/softwarecomposition/v1beta1/types.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go
  pkg/apis/softwarecomposition/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_openvulnerabilityexchangecontainer.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_softwarecomposition_client.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/openvulnerabilityexchangecontainer.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/softwarecomposition_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/interface.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/openvulnerabilityexchangecontainer.go
  pkg/generated/listers/softwarecomposition/v1beta1/expansion_generated.go
  pkg/generated/listers/softwarecomposition/v1beta1/openvulnerabilityexchangecontainer.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/softwarecomposition/openvulnerabilityexchange/etcd.go
  pkg/registry/softwarecomposition/openvulnerabilityexchange/strategy.go
Labels: enhancement

#45 fix: conform to the filesystem path limit
  pkg/registry/file/storage.go
  pkg/registry/file/storage_test.go
  pkg/registry/file/vulnerabilitysummarystorage.go
  pkg/registry/file/vulnerabilitysummarystorage_test.go
Labels: release, Refactoring, Bug fix

#56 Network neighbors
  artifacts/networkneighborses/01-example.yaml
  pkg/apis/softwarecomposition/network_types.go
  pkg/apis/softwarecomposition/register.go
  pkg/apis/softwarecomposition/v1beta1/network_types.go
  pkg/apis/softwarecomposition/v1beta1/register.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go
  pkg/apis/softwarecomposition/validation/validation.go
  pkg/apis/softwarecomposition/validation/validation_test.go
  pkg/apis/softwarecomposition/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_networkneighbors.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_softwarecomposition_client.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/networkneighbors.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/softwarecomposition_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/interface.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/networkneighbors.go
  pkg/generated/listers/softwarecomposition/v1beta1/expansion_generated.go
  pkg/generated/listers/softwarecomposition/v1beta1/networkneighbors.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/file/storage.go
  pkg/registry/file/storage_test.go
  pkg/registry/file/vulnerabilitysummarystorage.go
  pkg/registry/file/vulnerabilitysummarystorage_test.go
  pkg/registry/softwarecomposition/networkneighbors/etcd.go
  pkg/registry/softwarecomposition/networkneighbors/strategy.go
Labels: enhancement

#57 fix: return already exists error
  pkg/registry/file/storage.go
  pkg/registry/file/storage_test.go
  pkg/registry/file/vulnerabilitysummarystorage_test.go
Labels: release, Bug fix

#60 Load account from env var
  main.go
Labels: release, Refactoring

#59 Revert "fix: return already exists error"
  pkg/registry/file/storage.go
  pkg/registry/file/storage_test.go
  pkg/registry/file/vulnerabilitysummarystorage_test.go
Labels: release
