Repository kubescape/storage, pull requests merged in 2024-01, with the labels that each got.

#80 Fixed IP duplication
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy.go
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy_test.go
Labels: release, Tests, bug_fix

#81 fix cleanup of resources
  main.go
  pkg/cleanup/cleanup.go
  pkg/cleanup/discovery.go
Labels: enhancement, release, bug_fix

#83 Move NP generate to v1beta1
  pkg/apis/softwarecomposition/v1beta1/network_types.go
  pkg/apis/softwarecomposition/v1beta1/networkpolicy/networkpolicy.go
  pkg/apis/softwarecomposition/v1beta1/networkpolicy/networkpolicy_test.go
  pkg/apis/softwarecomposition/v1beta1/types.go
  pkg/registry/file/generatednetworkpolicy.go
  pkg/registry/file/generatednetworkpolicy_test.go
Labels: enhancement, release, Tests

#84 adding instructions to enable profiling
  README.md
Labels: documentation

#87 only return metadata inside watch events
  pkg/registry/file/storage.go
  pkg/registry/file/storage_test.go
  pkg/registry/file/watch_test.go
Labels: enhancement, release

#88 Remove labels
  pkg/apis/softwarecomposition/networkpolicy/labels.go
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy.go
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy_test.go
Labels: enhancement, release

#90 Ignore empty field
  go.mod
  go.sum
  pkg/apis/softwarecomposition/syfttypes.go
  pkg/apis/softwarecomposition/v1beta1/syfttypes.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release, Bug fix

#91 Fix/empty SBOM
  go.mod
  go.sum
  pkg/cleanup/cleanup.go
  pkg/cleanup/discovery.go
Labels: enhancement, release, Bug fix

#89 optimize memory profile of file storage
  pkg/apis/softwarecomposition/v1beta1/types.go
  pkg/cmd/server/start.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/file/storage.go
  pkg/registry/file/storage_test.go
Labels: enhancement, release

#92 fix network neighbors save
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy.go
  pkg/apis/softwarecomposition/validation/validation.go
  pkg/apis/softwarecomposition/validation/validation_test.go
  pkg/registry/file/storage.go
  pkg/registry/file/storage_test.go
  pkg/registry/softwarecomposition/applicationactivity/strategy.go
  pkg/registry/softwarecomposition/applicationprofile/strategy.go
  pkg/registry/softwarecomposition/applicationprofilesummary/strategy.go
  pkg/registry/softwarecomposition/configurationscansummary/strategy.go
  pkg/registry/softwarecomposition/generatednetworkpolicy/strategy.go
  pkg/registry/softwarecomposition/knownservers/strategy.go
  pkg/registry/softwarecomposition/networkneighbors/strategy.go
  pkg/registry/softwarecomposition/openvulnerabilityexchange/strategy.go
  pkg/registry/softwarecomposition/sbomspdxv2p3/strategy.go
  pkg/registry/softwarecomposition/sbomspdxv2p3filtered/strategy.go
  pkg/registry/softwarecomposition/sbomsummary/strategy.go
  pkg/registry/softwarecomposition/sbomsyftfiltereds/strategy.go
  pkg/registry/softwarecomposition/sbomsyfts/strategy.go
  pkg/registry/softwarecomposition/vulnerabilitymanifest/strategy.go
  pkg/registry/softwarecomposition/vulnerabilitymanifestsummary/strategy.go
  pkg/registry/softwarecomposition/vulnerabilitysummary/strategy.go
  pkg/registry/softwarecomposition/workloadconfigurationscans/strategy.go
  pkg/registry/softwarecomposition/workloadconfigurationscansummary/strategy.go
Labels: release, Bug fix

#93 Fix/cleanup
  go.mod
  go.sum
  main.go
  pkg/apis/softwarecomposition/networkpolicy.go
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy.go
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy_test.go
  pkg/apis/softwarecomposition/v1beta1/networkpolicy.go
  pkg/apis/softwarecomposition/v1beta1/networkpolicy/networkpolicy_test.go
  pkg/cleanup/cleanup.go
  pkg/cleanup/cleanup_test.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/file/generatednetworkpolicy.go
  pkg/registry/file/generatednetworkpolicy_test.go
Labels: enhancement, release, Bug fix, Review effort [1-5]: 4
