Repository kubescape/storage, pull requests merged in 2024-04, with the labels that each got.

#105 status update checks
  README.md
  pkg/registry/softwarecomposition/applicationprofile/strategy.go
  pkg/registry/softwarecomposition/applicationprofile/strategy_test.go
  pkg/registry/softwarecomposition/networkneighbors/strategy.go
  pkg/registry/softwarecomposition/networkneighbors/strategy_test.go
  pkg/utils/validations.go
  pkg/utils/validations_test.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 2

#106 support ephemeral containers
  pkg/apis/softwarecomposition/types.go
  pkg/apis/softwarecomposition/v1beta1/types.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go
  pkg/apis/softwarecomposition/zz_generated.deepcopy.go
  pkg/cleanup/discovery.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/file/processor.go
  pkg/registry/file/processor_test.go
Labels: enhancement, release, Review effort [1-5]: 3

#108 Fix MetadataType in artifacts
  pkg/apis/softwarecomposition/syfttypes.go
  pkg/apis/softwarecomposition/syfttypes_test.go
  pkg/apis/softwarecomposition/v1beta1/syfttypes.go
Labels: release, Tests, bug_fix, Review effort [1-5]: 2

#109 adding artifact
  pkg/apis/softwarecomposition/testdata/artifact.json
Labels: enhancement, release, Review effort [1-5]: 2

#107 add NetworkNeighborhood as a collection of NetworkNeighbors
  .dockerignore
  artifacts/networkneighborhood/01-example.yaml
  pkg/apis/softwarecomposition/network_types.go
  pkg/apis/softwarecomposition/networkpolicy/networkpolicy.go
  pkg/apis/softwarecomposition/register.go
  pkg/apis/softwarecomposition/types.go
  pkg/apis/softwarecomposition/v1beta1/network_types.go
  pkg/apis/softwarecomposition/v1beta1/networkpolicy/networkpolicy.go
  pkg/apis/softwarecomposition/v1beta1/register.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go
  pkg/apis/softwarecomposition/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/cleanup/cleanup.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_networkneighborhood.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/fake/fake_softwarecomposition_client.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/networkneighborhood.go
  pkg/generated/clientset/versioned/typed/softwarecomposition/v1beta1/softwarecomposition_client.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/interface.go
  pkg/generated/informers/externalversions/softwarecomposition/v1beta1/networkneighborhood.go
  pkg/generated/listers/softwarecomposition/v1beta1/expansion_generated.go
  pkg/generated/listers/softwarecomposition/v1beta1/networkneighborhood.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/file/applicationprofile_processor.go
  pkg/registry/file/applicationprofile_processor_test.go
  pkg/registry/file/networkneighborhood_processor.go
  pkg/registry/file/networkneighborhood_processor_test.go
  pkg/registry/file/processor.go
  pkg/registry/softwarecomposition/networkneighborhood/etcd.go
  pkg/registry/softwarecomposition/networkneighborhood/strategy.go
  pkg/registry/softwarecomposition/networkneighborhood/strategy_test.go
Labels: enhancement, release, Review effort [1-5]: 4

#110 reject updates on complete app profile, remove omitempty
  pkg/apis/softwarecomposition/v1beta1/types.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/registry/softwarecomposition/applicationprofile/strategy.go
  pkg/registry/softwarecomposition/applicationprofile/strategy_test.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 3

#111 bump syft
  go.mod
  go.sum
  pkg/apis/softwarecomposition/grype_types.go
  pkg/apis/softwarecomposition/packagemetadata/packagemetadata.go
  pkg/apis/softwarecomposition/sourcemetadata/sourcemetadata.go
  pkg/apis/softwarecomposition/syfttypes.go
  pkg/apis/softwarecomposition/syfttypes_test.go
  pkg/apis/softwarecomposition/testdata/artifact.json
  pkg/apis/softwarecomposition/v1beta1/grype_types.go
  pkg/apis/softwarecomposition/v1beta1/syfttypes.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go
  pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go
  pkg/apis/softwarecomposition/zz_generated.deepcopy.go
  pkg/generated/openapi/zz_generated.openapi.go
Labels: release

#112 add conversion for PackageBasicData from syft 0.101.1
  pkg/apis/softwarecomposition/syfttypes.go
  pkg/apis/softwarecomposition/syfttypes_test.go
  pkg/apis/softwarecomposition/testdata/artifact-v01011.json
  pkg/apis/softwarecomposition/v1beta1/syfttypes.go
Labels: release
