Repository kubescape/storage, pull requests merged in 2024-02, with the labels that each got.

#95 Ignore empty files
  pkg/cleanup/cleanup.go
Labels: Bug fix, Review effort [1-5]: 2

#94 add presave processor to deduplicate profile info
  pkg/apis/softwarecomposition/types.go
  pkg/apis/softwarecomposition/types_test.go
  pkg/apiserver/apiserver.go
  pkg/registry/file/processor.go
  pkg/registry/file/storage.go
  pkg/registry/file/storage_test.go
  pkg/utils/mutex.go
  pkg/utils/mutex_test.go
Labels: enhancement, release, Review effort [1-5]: 4

#97 Fix errors in logs
  pkg/registry/file/storage.go
  pkg/utils/mutex.go
  pkg/utils/mutex_test.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 4

#99 prevent race condition on watcher.stopped
  pkg/registry/file/watch.go
Labels: release
